root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/cutflow_126893_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WZ_SusySel.root\")"
# 
# root -l "run_root_TSelector_SusySel_fake.C(\"xxx\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/ZPlusJets_SusySel.root\")"
# 
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/ZZ_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/Higgs_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/ttbar_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WW_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WWPlusJets_SusySel.root\")"

#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177501_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177502_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177503_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177504_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177505_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177506_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177507_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177508_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177509_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177510_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177511_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177512_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177513_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177514_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177515_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177516_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177517_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177518_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177519_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177520_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177521_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177522_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177523_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177524_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177525_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177526_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177527_SusySel.root\")"
