root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/cutflow_126893_SusySel_new.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WZ_skimslim_SusySel.root\")"
# 
# root -l "run_root_TSelector_SusySel_fake.C(\"xxx\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/ZPlusJets_skimslim_SusySel.root\")"
# 
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/ZZ_skimslim_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/Higgs_skimslim_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/ttbar_skimslim_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WW_skimslim_SusySel.root\")"
# root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WWPlusJets_skimslim_SusySel.root\")"
# 
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177501_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177502_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177503_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177504_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177505_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177506_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177507_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177508_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177509_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177510_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177511_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177512_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177513_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177514_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177515_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177516_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177517_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177518_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177519_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177520_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177521_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177522_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177523_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177524_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177525_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177526_skimslim_SusySel.root\")"
#  root -l "run_root_TSelector_SusySel.C(\"/data/etp3/jwittkow/analysis_SUSYTools_03_04/WH_177527_skimslim_SusySel.root\")"
